server:
  port: ${TODO_APP_PORT:8080}
spring:
    application:
      name: todo-app
    data:
     mongodb:
       username: ${MONGO_USER:bapaydin67}
       password: ${MONGO_PASSWORD:12345678}
       host: ${MONGO_HOST:ds113046.mlab.com}
       database: ${MONGO_DB:assignment}
       port: ${MONGO_DB_PORT:13046}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
