server:
  port: ${EUREKA_SERVER_PORT:8761}
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

